# Generated by Django 5.1.2 on 2025-04-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название страны')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название языка')),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Уровень журнала')),
            ],
        ),
        migrations.CreateModel(
            name='OpenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Открытый доступ',
                'verbose_name_plural': 'Открытый доступ',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.IntegerField(verbose_name='Номер научного журнала')),
                ('subjects', models.JSONField(default=list, verbose_name='Тематики')),
                ('impact_factor', models.FloatField(blank=True, null=True, verbose_name='Импакт-фактор')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language', verbose_name='Язык')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.levels', verbose_name='Уровень научного журнала')),
                ('open_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.openaccess', verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
    ]
