# Generated by Django 5.1.4 on 2025-04-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык журнала', 'verbose_name_plural': 'Язык журнала'},
        ),
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name': 'Уровни журнала', 'verbose_name_plural': 'Уровни журнала'},
        ),
    ]
