# Generated by Django 5.1.4 on 2025-04-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_country_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна'),
        ),
    ]
