# Generated by Django 5.2 on 2025-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_journal_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='links',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
