# Generated by Django 5.2 on 2025-05-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_journal_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='links',
        ),
        migrations.AddField(
            model_name='journal',
            name='external_links',
            field=models.JSONField(blank=True, default={'elibrary': None, 'official': None, 'openalex': None, 'wikidata': None}, verbose_name='Внешние ссылки'),
        ),
    ]
