# Generated by Django 5.1.4 on 2025-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_journal_issn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='external_links',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='impact_factor',
        ),
        migrations.AddField(
            model_name='journal',
            name='h_index',
            field=models.FloatField(blank=True, null=True, verbose_name='Индекс Хирша'),
        ),
    ]
