# Generated by Django 5.2 on 2025-05-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_journal_open_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Название научного журнала'),
            preserve_default=False,
        ),
    ]
