# Generated by Django 5.2 on 2025-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_mal',
            field=models.CharField(default=1, max_length=155, verbose_name='Краткая расшифровка'),
            preserve_default=False,
        ),
    ]
