# Generated by Django 5.2 on 2025-06-26 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_country_name_mal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.language', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.levels', verbose_name='Уровень научного журнала'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='open_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Тип доступа'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='subjects',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Тематики'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название научного журнала'),
        ),
    ]
